# Generated by Django 4.1.4 on 2022-12-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tagger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='value',
        ),
    ]
